/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author UNIVALLE
 */
public class VistaMenuSTY extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuSTY
     */
    public VistaMenuSTY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_vehiculo = new javax.swing.JButton();
        jbtn_propietario = new javax.swing.JButton();
        jbtn_tarjetaPropiedad = new javax.swing.JButton();
        jbtn_listarVehiculos = new javax.swing.JButton();
        jbtn_listarPropietarios = new javax.swing.JButton();
        jbtn_listarTarjetas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secretaría de Tránsito Yumboslavia");
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_vehiculo.setText("Ingresar Vehículo");
        getContentPane().add(jbtn_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 73, 200, -1));

        jbtn_propietario.setText("Gestión Propietarios");
        getContentPane().add(jbtn_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 126, 200, -1));

        jbtn_tarjetaPropiedad.setText("Ingresar Tarjeta Propiedad");
        getContentPane().add(jbtn_tarjetaPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, -1));

        jbtn_listarVehiculos.setText("Listar Vehículos");
        getContentPane().add(jbtn_listarVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 73, 150, -1));

        jbtn_listarPropietarios.setText("Listar Propietarios");
        getContentPane().add(jbtn_listarPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 126, 150, -1));

        jbtn_listarTarjetas.setText("Listar Tarjetas");
        getContentPane().add(jbtn_listarTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 178, 150, -1));

        setSize(new java.awt.Dimension(455, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuSTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuSTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuSTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuSTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuSTY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_listarPropietarios;
    public javax.swing.JButton jbtn_listarTarjetas;
    public javax.swing.JButton jbtn_listarVehiculos;
    public javax.swing.JButton jbtn_propietario;
    public javax.swing.JButton jbtn_tarjetaPropiedad;
    public javax.swing.JButton jbtn_vehiculo;
    // End of variables declaration//GEN-END:variables
}
